; From Mathlib/RingTheory/Polynomial/Chebyshev.lean/T_add_two
(set-option :smt.mbqi true)
(declare-fun T (Int) Real)
(declare-const x Real)
(assert (forall ((n Int)) (= (T (+ n 2)) (- (* 2 (* x (T (+ n 1)))) (T n)))))
(declare-const m Int)
(assert (forall ((k Int)) (= (* 2 (* (T m) (T (+ m k)))) (+ (T (+ (* 2 m) k)) (T k)))))
(assert (forall ((k Int)) (= (* 2 (* (T (+ m 1)) (T (+ (+ m 1) k)))) (+ (T (+ (* 2 (+ m 1)) k)) (T k)))))
(declare-const k Int)
(assert (not (= (* 2 (* (T (+ m 2)) (T (+ (+ m 2) k)))) (+ (T (+ (* 2 (+ m 2)) k)) (T k)))))
(check-sat)